[package]
edition = "2021"
name = "pedalboard-midi"
version = "0.1.2"
readme = "README.md"
description = "Midi Pedalboard based on rp2040"
license-file = "LICENSE.md"
documentation = "README.md"
homepage = "https://github.com/pedalboard"
repository = "https://github.com/pedalboard/pedalboard-midi"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = { version = "0.2.7", features = ["unproven"] }

defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

rp-pico = "0.7"

cortex-m-rtic = "1.1.4"
rp2040-monotonic = "1.2.0"
rp2040-hal = { version = "0.8.1", features = ["eh1_0_alpha", "defmt"] }
usb-device = { version="0.2.9", features = ["defmt"] }
usbd-midi = { git = "https://github.com/rust-midi/usbd-midi", branch = "main" }
nb = { version="1.1.0" }
fugit = "0.3"
embedded-midi = { git = "https://github.com/rust-midi/embedded-midi", branch = "main" }
midi-types = { version = "0.1.7", features = ["defmt"] }
midi-convert = "0.1.3"
debouncr = "0.2.2"
rotary-encoder-embedded = "0.2.0"
heapless = "0.7.16"
movavg = { version = "2.2.0", default-features = false }
smart-leds = "0.3.0"
ws2812-spi = "0.4.0"
colorous = {version = "1.0.10", default-features = false }

# [dev-dependencies]

[features]
hw-v1 = []

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
