//! Config/diagnostic mode state machine.
//!
//! Entry: both encoder buttons held simultaneously for >1 second.
//! Exit: both encoder buttons held simultaneously again (>1 second).
//!
//! While active, all normal input processing is suppressed. Instead:
//! - Button presses show which button + what MIDI it would send
//! - Encoder turns show raw direction + mapped value
//! - Expression pedals show raw ADC value (for calibration)
//! - Idle shows firmware version, preset count, global config summary

use crate::events::{Edge, InputEvent, Pulse};
use core::fmt::Write;
use heapless::String;

/// How long both encoder buttons must be held to enter/exit config mode (in ms).
const ENTRY_HOLD_MS: u32 = 1000;

/// Display event generated by config mode for the display task.
#[derive(Debug, Clone)]
pub enum ConfigDisplayEvent {
    /// Show the idle/info screen (firmware version, preset count, etc.)
    Info(InfoScreen),
    /// Show button press feedback.
    ButtonPress {
        button: &'static str,
        detail: String<40>,
    },
    /// Show button release feedback.
    ButtonRelease { button: &'static str },
    /// Show encoder turn feedback with MIDI output info.
    EncoderTurn {
        encoder: &'static str,
        direction: &'static str,
        detail: String<40>,
    },
    /// Show expression pedal raw ADC + MIDI output info.
    ExpressionPedal {
        pedal: &'static str,
        raw_adc: u16,
        detail: String<40>,
    },
    /// Incoming MIDI message for the debug log (right display).
    MidiIn { data: [u8; 3], len: u8 },
    /// Outgoing MIDI message for the debug log (right display).
    MidiOut { data: [u8; 3], len: u8 },
    /// Config mode entered — clear display and show entry message.
    Entered,
    /// Config mode exited — return to normal display.
    Exited,
}

/// Info screen content.
#[derive(Debug, Clone)]
pub struct InfoScreen {
    pub firmware_version: &'static str,
    pub git_hash: &'static str,
    pub preset_count: u8,
    pub din_enabled: bool,
    pub midi_clock: bool,
    pub bpm: u16,
    pub din_to_usb_thru: bool,
    pub usb_to_din_thru: bool,
    pub usb_to_usb_thru: bool,
}

/// Config mode state machine.
pub struct ConfigMode {
    /// Whether config mode is currently active.
    active: bool,
    /// Timestamp when both buttons were first detected as held.
    both_held_since: Option<u32>,
    /// Track individual button states.
    vol_held: bool,
    gain_held: bool,
    /// Suppress entry/exit retriggering until both buttons are released.
    suppress_until_release: bool,
}

impl Default for ConfigMode {
    fn default() -> Self {
        Self::new()
    }
}

impl ConfigMode {
    pub fn new() -> Self {
        Self {
            active: false,
            both_held_since: None,
            vol_held: false,
            gain_held: false,
            suppress_until_release: false,
        }
    }

    /// Returns true if config mode is currently active.
    pub fn is_active(&self) -> bool {
        self.active
    }

    /// Returns true if both encoder buttons are held and we're waiting for the hold threshold.
    pub fn is_holding(&self) -> bool {
        self.both_held_since.is_some()
    }

    /// Process input events. Returns a display event if something should be shown.
    /// When config mode is active, this consumes all events (caller should not pass them
    /// to the normal PE handler).
    ///
    /// `now_ms` is the current monotonic time in milliseconds.
    /// `preset_count` and config info are used for the idle screen.
    pub fn process_events(
        &mut self,
        events: &[InputEvent],
        now_ms: u32,
        context: &ConfigContext,
    ) -> heapless::Vec<ConfigDisplayEvent, 4> {
        let mut display_events: heapless::Vec<ConfigDisplayEvent, 4> = heapless::Vec::new();

        // Track encoder button state from events.
        for event in events {
            match event {
                InputEvent::VolButton(Edge::Activate) => self.vol_held = true,
                InputEvent::VolButton(Edge::Deactivate) => {
                    self.vol_held = false;
                    self.suppress_until_release = false;
                }
                InputEvent::GainButton(Edge::Activate) => self.gain_held = true,
                InputEvent::GainButton(Edge::Deactivate) => {
                    self.gain_held = false;
                    self.suppress_until_release = false;
                }
                _ => {}
            }
        }

        // Entry/exit detection: both held for ENTRY_HOLD_MS.
        if self.vol_held && self.gain_held && !self.suppress_until_release {
            match self.both_held_since {
                None => {
                    self.both_held_since = Some(now_ms);
                }
                Some(since) => {
                    if now_ms.wrapping_sub(since) >= ENTRY_HOLD_MS {
                        self.active = !self.active;
                        self.both_held_since = None;
                        self.suppress_until_release = true;

                        if self.active {
                            display_events.push(ConfigDisplayEvent::Entered).ok();
                            display_events
                                .push(ConfigDisplayEvent::Info(InfoScreen {
                                    firmware_version: context.firmware_version,
                                    git_hash: context.git_hash,
                                    preset_count: context.preset_count,
                                    din_enabled: context.din_enabled,
                                    midi_clock: context.midi_clock,
                                    bpm: context.bpm,
                                    din_to_usb_thru: context.din_to_usb_thru,
                                    usb_to_din_thru: context.usb_to_din_thru,
                                    usb_to_usb_thru: context.usb_to_usb_thru,
                                }))
                                .ok();
                        } else {
                            display_events.push(ConfigDisplayEvent::Exited).ok();
                        }
                        return display_events;
                    }
                }
            }
        } else {
            self.both_held_since = None;
        }

        // If not active, nothing else to do.
        if !self.active {
            return display_events;
        }

        // Process events for diagnostic display.
        for event in events {
            match event {
                InputEvent::ButtonA(Edge::Activate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonPress {
                            button: "A",
                            detail: button_detail(context, 0),
                        })
                        .ok();
                }
                InputEvent::ButtonB(Edge::Activate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonPress {
                            button: "B",
                            detail: button_detail(context, 1),
                        })
                        .ok();
                }
                InputEvent::ButtonC(Edge::Activate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonPress {
                            button: "C",
                            detail: button_detail(context, 2),
                        })
                        .ok();
                }
                InputEvent::ButtonD(Edge::Activate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonPress {
                            button: "D",
                            detail: button_detail(context, 3),
                        })
                        .ok();
                }
                InputEvent::ButtonE(Edge::Activate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonPress {
                            button: "E",
                            detail: button_detail(context, 4),
                        })
                        .ok();
                }
                InputEvent::ButtonF(Edge::Activate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonPress {
                            button: "F",
                            detail: button_detail(context, 5),
                        })
                        .ok();
                }
                InputEvent::ButtonA(Edge::Deactivate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonRelease { button: "A" })
                        .ok();
                }
                InputEvent::ButtonB(Edge::Deactivate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonRelease { button: "B" })
                        .ok();
                }
                InputEvent::ButtonC(Edge::Deactivate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonRelease { button: "C" })
                        .ok();
                }
                InputEvent::ButtonD(Edge::Deactivate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonRelease { button: "D" })
                        .ok();
                }
                InputEvent::ButtonE(Edge::Deactivate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonRelease { button: "E" })
                        .ok();
                }
                InputEvent::ButtonF(Edge::Deactivate) => {
                    display_events
                        .push(ConfigDisplayEvent::ButtonRelease { button: "F" })
                        .ok();
                }
                InputEvent::Vol(pulse) => {
                    let dir = match pulse {
                        Pulse::Clockwise => "CW",
                        Pulse::CounterClockwise => "CCW",
                    };
                    let mut detail: String<40> = String::new();
                    if !context.encoder_configs[0].summary.is_empty() {
                        write!(detail, "{} {}", context.encoder_configs[0].summary, dir).ok();
                    } else {
                        write!(detail, "{}", dir).ok();
                    }
                    display_events
                        .push(ConfigDisplayEvent::EncoderTurn {
                            encoder: "Vol",
                            direction: dir,
                            detail,
                        })
                        .ok();
                }
                InputEvent::Gain(pulse) => {
                    let dir = match pulse {
                        Pulse::Clockwise => "CW",
                        Pulse::CounterClockwise => "CCW",
                    };
                    let mut detail: String<40> = String::new();
                    if !context.encoder_configs[1].summary.is_empty() {
                        write!(detail, "{} {}", context.encoder_configs[1].summary, dir).ok();
                    } else {
                        write!(detail, "{}", dir).ok();
                    }
                    display_events
                        .push(ConfigDisplayEvent::EncoderTurn {
                            encoder: "Gain",
                            direction: dir,
                            detail,
                        })
                        .ok();
                }
                InputEvent::ExpressionPedal1(raw) => {
                    let mut detail: String<40> = String::new();
                    if !context.analog_configs[1].summary.is_empty() {
                        write!(detail, "{}", context.analog_configs[1].summary).ok();
                    } else {
                        write!(detail, "(no mapping)").ok();
                    }
                    display_events
                        .push(ConfigDisplayEvent::ExpressionPedal {
                            pedal: "Exp1",
                            raw_adc: *raw,
                            detail,
                        })
                        .ok();
                }
                InputEvent::ExpressionPedal2(raw) => {
                    let mut detail: String<40> = String::new();
                    if !context.analog_configs[0].summary.is_empty() {
                        write!(detail, "{}", context.analog_configs[0].summary).ok();
                    } else {
                        write!(detail, "(no mapping)").ok();
                    }
                    display_events
                        .push(ConfigDisplayEvent::ExpressionPedal {
                            pedal: "Exp2",
                            raw_adc: *raw,
                            detail,
                        })
                        .ok();
                }
                // Encoder button events already handled above for entry/exit.
                InputEvent::VolButton(_) | InputEvent::GainButton(_) => {}
            }
        }

        display_events
    }
}

/// Context provided by the caller for generating display content.
pub struct ConfigContext<'a> {
    pub firmware_version: &'static str,
    pub git_hash: &'static str,
    pub preset_count: u8,
    pub din_enabled: bool,
    pub midi_clock: bool,
    pub bpm: u16,
    pub din_to_usb_thru: bool,
    pub usb_to_din_thru: bool,
    pub usb_to_usb_thru: bool,
    /// First action of each button in current preset (for display).
    pub button_actions: &'a [ButtonAction; 6],
    /// Encoder config summaries (Vol, Gain).
    pub encoder_configs: [EncoderInfo; 2],
    /// Analog/expression config summaries (Exp1, Exp2).
    pub analog_configs: [AnalogInfo; 2],
}

/// Summary of an encoder's MIDI output for config mode display.
#[derive(Debug, Clone, Default)]
pub struct EncoderInfo {
    /// e.g., "CC 7 ch1" or "Preset scroll" or "" if unconfigured.
    pub summary: String<24>,
}

/// Summary of an analog input's MIDI output for config mode display.
#[derive(Debug, Clone, Default)]
pub struct AnalogInfo {
    /// e.g., "CC 11 ch1" or "" if unconfigured.
    pub summary: String<24>,
}

/// Summary of a button's primary action for display in config mode.
#[derive(Debug, Clone, Default)]
pub struct ButtonAction {
    /// e.g., "CC 80 ch1", "PC 3 ch2", "Note 60 ch1", or "" if unconfigured.
    pub summary: String<24>,
}

/// Generate the detail string for a button press in config mode.
fn button_detail(context: &ConfigContext, index: usize) -> String<40> {
    let mut s: String<40> = String::new();
    if index < context.button_actions.len() && !context.button_actions[index].summary.is_empty() {
        write!(s, "{}", context.button_actions[index].summary).ok();
    } else {
        write!(s, "(unconfigured)").ok();
    }
    s
}

/// Build a ButtonAction summary from preset config.
pub fn summarize_button(preset: &midi_controller::config::Preset, index: usize) -> ButtonAction {
    use midi_controller::config::Action;

    let mut action = ButtonAction::default();

    let Some(btn) = preset.buttons.get(index) else {
        return action;
    };

    // Look at on_press actions for the primary action summary.
    if let Some(first) = btn.on_press.first() {
        match first {
            Action::Midi { data, len } => {
                let l = *len as usize;
                if l >= 2 {
                    let msg_type = data[0] & 0xF0;
                    let channel = (data[0] & 0x0F) + 1;
                    match msg_type {
                        0xB0 if l >= 3 => {
                            write!(action.summary, "CC {} v{} ch{}", data[1], data[2], channel)
                                .ok();
                        }
                        0x90 if l >= 3 => {
                            write!(action.summary, "Note {} ch{}", data[1], channel).ok();
                        }
                        0xC0 => {
                            write!(action.summary, "PC {} ch{}", data[1], channel).ok();
                        }
                        _ => {
                            write!(action.summary, "MIDI {:02X}", data[0]).ok();
                        }
                    }
                }
            }
            Action::CcCycle { cc, channel, .. } => {
                write!(action.summary, "CC {} cycle ch{}", cc, channel).ok();
            }
            Action::Delay(ms) => {
                write!(action.summary, "Delay {}ms", ms).ok();
            }
            Action::PresetSelect(idx) => {
                write!(action.summary, "Preset {}", idx).ok();
            }
            Action::PresetNext => {
                write!(action.summary, "Next preset").ok();
            }
            Action::PresetPrev => {
                write!(action.summary, "Prev preset").ok();
            }
            _ => {
                write!(action.summary, "(action)").ok();
            }
        }
    } else if !btn.cycle_values.is_empty() {
        write!(action.summary, "Cycle").ok();
    }

    action
}

/// Build an EncoderInfo summary from preset config.
pub fn summarize_encoder(preset: &midi_controller::config::Preset, index: usize) -> EncoderInfo {
    use midi_controller::config::EncoderAction;

    let mut info = EncoderInfo::default();

    let Some(enc) = preset.encoders.get(index) else {
        return info;
    };

    match &enc.action {
        EncoderAction::Cc { cc, channel, .. } => {
            write!(info.summary, "CC {} ch{}", cc, channel).ok();
        }
        EncoderAction::CcRelative { cc, channel, .. } => {
            write!(info.summary, "CC {} rel ch{}", cc, channel).ok();
        }
        EncoderAction::PresetScroll => {
            write!(info.summary, "Preset scroll").ok();
        }
    }

    info
}

/// Build an AnalogInfo summary from preset config.
pub fn summarize_analog(preset: &midi_controller::config::Preset, index: usize) -> AnalogInfo {
    let mut info = AnalogInfo::default();

    let Some(analog) = preset.analog.get(index) else {
        return info;
    };

    write!(info.summary, "CC {} ch{}", analog.cc, analog.channel).ok();

    info
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entry_requires_hold_duration() {
        let mut cm = ConfigMode::new();
        let context = test_context();

        // Press both encoder buttons.
        let events = [
            InputEvent::VolButton(Edge::Activate),
            InputEvent::GainButton(Edge::Activate),
        ];
        let result = cm.process_events(&events, 0, &context);
        assert!(!cm.is_active());
        assert!(result.is_empty());

        // Not enough time has passed.
        let result = cm.process_events(&[], 500, &context);
        assert!(!cm.is_active());
        assert!(result.is_empty());

        // Now enough time (1000ms).
        let result = cm.process_events(&[], 1000, &context);
        assert!(cm.is_active());
        assert!(result
            .iter()
            .any(|e| matches!(e, ConfigDisplayEvent::Entered)));
    }

    #[test]
    fn exit_requires_release_first() {
        let mut cm = ConfigMode::new();
        let context = test_context();

        // Enter config mode.
        let events = [
            InputEvent::VolButton(Edge::Activate),
            InputEvent::GainButton(Edge::Activate),
        ];
        cm.process_events(&events, 0, &context);
        cm.process_events(&[], 1000, &context);
        assert!(cm.is_active());

        // Must release both buttons before re-entry detection works.
        let events = [
            InputEvent::VolButton(Edge::Deactivate),
            InputEvent::GainButton(Edge::Deactivate),
        ];
        cm.process_events(&events, 1100, &context);

        // Press both again.
        let events = [
            InputEvent::VolButton(Edge::Activate),
            InputEvent::GainButton(Edge::Activate),
        ];
        cm.process_events(&events, 1200, &context);
        cm.process_events(&[], 2200, &context);
        assert!(!cm.is_active());
    }

    #[test]
    fn button_press_generates_event() {
        let mut cm = ConfigMode::new();
        let context = test_context();

        // Enter config mode.
        let events = [
            InputEvent::VolButton(Edge::Activate),
            InputEvent::GainButton(Edge::Activate),
        ];
        cm.process_events(&events, 0, &context);
        cm.process_events(&[], 1000, &context);
        assert!(cm.is_active());

        // Press button A.
        let events = [InputEvent::ButtonA(Edge::Activate)];
        let result = cm.process_events(&events, 1100, &context);
        assert!(result
            .iter()
            .any(|e| matches!(e, ConfigDisplayEvent::ButtonPress { button: "A", .. })));
    }

    #[test]
    fn expression_pedal_generates_event() {
        let mut cm = ConfigMode::new();
        let context = test_context();

        // Enter config mode.
        let events = [
            InputEvent::VolButton(Edge::Activate),
            InputEvent::GainButton(Edge::Activate),
        ];
        cm.process_events(&events, 0, &context);
        cm.process_events(&[], 1000, &context);
        assert!(cm.is_active());

        // Move expression pedal.
        let events = [InputEvent::ExpressionPedal1(2048)];
        let result = cm.process_events(&events, 1100, &context);
        assert!(result.iter().any(|e| matches!(
            e,
            ConfigDisplayEvent::ExpressionPedal {
                pedal: "Exp1",
                raw_adc: 2048,
                ..
            }
        )));
    }

    #[test]
    fn not_active_suppresses_button_events() {
        let mut cm = ConfigMode::new();
        let context = test_context();

        // Press button A while NOT in config mode.
        let events = [InputEvent::ButtonA(Edge::Activate)];
        let result = cm.process_events(&events, 0, &context);
        assert!(result.is_empty());
    }

    fn test_context() -> ConfigContext<'static> {
        static ACTIONS: [ButtonAction; 6] = [
            ButtonAction {
                summary: String::new(),
            },
            ButtonAction {
                summary: String::new(),
            },
            ButtonAction {
                summary: String::new(),
            },
            ButtonAction {
                summary: String::new(),
            },
            ButtonAction {
                summary: String::new(),
            },
            ButtonAction {
                summary: String::new(),
            },
        ];
        ConfigContext {
            firmware_version: "0.1.0",
            git_hash: "abc1234",
            preset_count: 3,
            din_enabled: true,
            midi_clock: false,
            bpm: 120,
            din_to_usb_thru: true,
            usb_to_din_thru: false,
            usb_to_usb_thru: false,
            button_actions: &ACTIONS,
            encoder_configs: [EncoderInfo::default(), EncoderInfo::default()],
            analog_configs: [AnalogInfo::default(), AnalogInfo::default()],
        }
    }
}
